package it.polimi.ingsw.enumeration;

public enum ImageEnum {
    DEV0("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-1-1.png","DEV0"),
    DEV1("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-2-1.png","DEV1"),
    DEV2("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-3-1.png","DEV2"),
    DEV3("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-4-1.png","DEV3"),
    DEV4("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-5-1.png","DEV4"),
    DEV5("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-6-1.png","DEV5"),
    DEV6("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-7-1.png","DEV6"),
    DEV7("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-8-1.png","DEV7"),
    DEV8("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-9-1.png","DEV8"),
    DEV9("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-10-1.png","DEV9"),
    DEV10("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-11-1.png","DEV10"),
    DEV11("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-12-1.png","DEV11"),
    DEV12("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-13-1.png","DEV12"),
    DEV13("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-14-1.png","DEV13"),
    DEV14("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-15-1.png","DEV14"),
    DEV15("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-16-1.png","DEV15"),
    DEV16("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-17-1.png","DEV16"),
    DEV17("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-18-1.png","DEV17"),
    DEV18("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-19-1.png","DEV18"),
    DEV19("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-20-1.png","DEV19"),
    DEV20("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-21-1.png","DEV20"),
    DEV21("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-22-1.png","DEV21"),
    DEV22("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-23-1.png","DEV22"),
    DEV23("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-24-1.png","DEV23"),
    DEV24("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-25-1.png","DEV24"),
    DEV25("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-26-1.png","DEV25"),
    DEV26("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-27-1.png","DEV26"),
    DEV27("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-28-1.png","DEV27"),
    DEV28("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-29-1.png","DEV28"),
    DEV29("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-30-1.png","DEV29"),
    DEV30("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-31-1.png","DEV30"),
    DEV31("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-32-1.png","DEV31"),
    DEV32("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-33-1.png","DEV32"),
    DEV33("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-34-1.png","DEV33"),
    DEV34("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-35-1.png","DEV34"),
    DEV35("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-36-1.png","DEV35"),
    DEV36("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-37-1.png","DEV36"),
    DEV37("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-38-1.png","DEV37"),
    DEV38("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-39-1.png","DEV38"),
    DEV39("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-40-1.png","DEV39"),
    DEV40("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-41-1.png","DEV40"),
    DEV41("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-42-1.png","DEV41"),
    DEV42("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-43-1.png","DEV42"),
    DEV43("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-44-1.png","DEV43"),
    DEV44("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-45-1.png","DEV44"),
    DEV45("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-46-1.png","DEV45"),
    DEV46("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-47-1.png","DEV46"),
    DEV47("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-48-1.png","DEV47"),
    DEV48("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-49-1.png","DEV48"),
    LEADER0("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-50-1.png","LEADER0"),
    LEADER1("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-51-1.png","LEADER1"),
    LEADER2("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-52-1.png","LEADER2"),
    LEADER3("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-53-1.png","LEADER3"),
    LEADER4("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-54-1.png","LEADER4"),
    LEADER5("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-55-1.png","LEADER5"),
    LEADER6("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-56-1.png","LEADER6"),
    LEADER7("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-57-1.png","LEADER7"),
    LEADER8("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-58-1.png","LEADER8"),
    LEADER9("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-59-1.png","LEADER9"),
    LEADER10("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-60-1.png","LEADER10"),
    LEADER11("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-61-1.png","LEADER11"),
    LEADER12("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-62-1.png","LEADER12"),
    LEADER13("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-63-1.png","LEADER13"),
    LEADER14("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-64-1.png","LEADER14"),
    LEADER15("src/main/resources/pics/front/Masters of Renaissance_Cards_FRONT_3mmBleed_1-65-1.png","LEADER15"),
    BOARD1("src/main/resources/pics/board/Board1.png","BOARD1"),
    BOARD2("src/main/resources/pics/board/Board2.png","BOARD2"),
    BLUE("src/main/resources/pics/marble/BlueMarble.png","BLUE"),
    GREY("src/main/resources/pics/marble/GreyMarble.png","GREY"),
    PURPLE("src/main/resources/pics/marble/PurpleMarble.png","PURPLE"),
    RED("src/main/resources/pics/marble/RedMarble.png","RED"),
    WHITE("src/main/resources/pics/marble/WhiteMarble.png","WHITE"),
    YELLOW("src/main/resources/pics/marble/YellowMarble.png","YELLOW"),
    INKWELL("src/main/resources/pics/punchboard/calamaio.png","INKWELL"),
    BLUE_CARD_MINUS2("src/main/resources/pics/punchboard/cerchio1.png","BLUE_CARD_MINUS2"),
    GREEN_CARD_MINUS2("src/main/resources/pics/punchboard/cerchio2.png","GREEN_CARD_MINUS2"),
    PURPLE_CARD_MINUS2("src/main/resources/pics/punchboard/cerchio3.png","PURPLE_CARD_MINUS2"),
    YELLOW_CARD_MINUS2("src/main/resources/pics/punchboard/cerchio4.png","YELLOW_CARD_MINUS2"),
    FORWARD_BY_2_BLACK("src/main/resources/pics/punchboard/cerchio5.png","FORWARD_BY_2_BLACK"),
    FORWARD_SHUFFLE("src/main/resources/pics/punchboard/cerchio7.png","FORWARD_SHUFFLE"),
    COIN("src/main/resources/pics/punchboard/coin.png","COIN"),
    COIN2("src/main/resources/pics/punchboard/coin2.png","COIN2"),
    SERVANT("src/main/resources/pics/punchboard/servant.png","SERVANT"),
    SERVANT2("src/main/resources/pics/punchboard/servant2.png","SERVANT2"),
    SHIELD("src/main/resources/pics/punchboard/shield.png","SHIELD"),
    SHIELD2("src/main/resources/pics/punchboard/shield2.png","SHIELD2"),
    STONE("src/main/resources/pics/punchboard/stone.png","STONE"),
    STONE2("src/main/resources/pics/punchboard/stone2.png","STONE2"),
    LORENZO("src/main/resources/pics/punchboard/lorenzo.png","LORENZO"),
    PPF1F("src/main/resources/pics/punchboard/pope_favor1_front.png","PPF1F"),
    PPF1B("src/main/resources/pics/punchboard/pope_favor1_back.png","PPF1B"),
    PPF2F("src/main/resources/pics/punchboard/pope_favor2_front.png","PPF2F"),
    PPF2B("src/main/resources/pics/punchboard/pope_favor2_back.png","PPF2B"),
    PPF3F("src/main/resources/pics/punchboard/pope_favor3_front.png","PPF3F"),
    PPF3B("src/main/resources/pics/punchboard/pope_favor3_back.png","PPF3B");





    private String url;
    private String name;

    private ImageEnum(String url, String name) {
        this.url=url;
        this.name=name;
    }
}


